Map<String, String> french = {
  'HOME': 'Maison',
  'HISTORY': 'Histoire',
  'PROFILE': 'Profil',
  'COMPLETE_DELIVERY': 'Livraison complète',
  'RETURN_DELIVERY': 'Livraison de retour',
  'ACTIVE_ORDERS': 'Commandes actives',
  'SEE_DETAILS': 'Voir les détails',
  'GET_DIRECTION': 'Obtenir litinéraire',
  'ORDER_ID': 'Numéro de commande : ',
  'SEE_ORDER_DETAILS': 'Voir les détails de la commande',
  'CONFIRM_DELIVERY': 'Confirmer la livraison',
  'CUSTOMER': 'Cliente',
  'ORDER_DETAILS': 'détails de la commande',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Votre estimation du délai de livraison',
  'PAYMENT_INFO': 'Payment Info',
  'METHOD': 'Méthode : ',
  'STATUS': 'Statut : ',
  'ORDER_SUMMERY': 'Récapitulatif de la commande',
  'SIZE': 'Taille: ',
  'ORDER_HISTORY': 'Historique des commandes',
  'EXTRAS': 'Suppléments',
  'ADDON': 'Ajouter: ',
  'INSTRUCTIONS': 'Des instructions: ',
  'SUBTOTAL': 'total',
  'DISCOUNT': 'Remise',
  'DELIVERY_CHARGE': 'Frais de livraison',
  "DELIVERY_ADDRESS": "Adresse de livraison",
  'TOTAL': 'Total',
  'CONFIRM_DELIVERY_ALERT': 'Êtes-vous sûr de confirmer la livraison ?',
  'NO_CANCEL': 'Non, Annuler',
  'YES_CONFIRM': 'Oui, Confirmer',
  'CASH_ON_DELIVERY': 'Paiement à la livraison',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Commande livrée avec succès',
  'BACK_TO_HOME': 'De retour à la maison',
  'OPEN': 'Ouverte',
  'MY_PROFILE': 'Mon profil',
  'BRANCH': 'Bifurquer',
  'LOG_OUT': 'Se déconnecter',
  'CHANGE_PASSWORD': 'Changer le mot de passe',
  'CHANGE_LANGUAGE': 'Changer de langue',
  'TERMS_CONDITION': 'Termes et conditions',
  'PRIVACY_POLICY': 'Politique de confidentialité',
  'EDIT_PROFILE': 'Termes et conditions',
  'FIRST_NAME': 'Prénom',
  'LAST_NAME': 'Nom de famille',
  'EMAIL': 'E-mail',
  'MOBILE_NUMBER': 'Numéro de portable',
  'UPDATE_PROFILE': 'Mettre à jour le profil',
  'OLD_PASSWORD': 'ancien mot de passe',
  'NEW_PASSWORD': 'nouveau mot de passe',
  'RETYPE_NEW_PASSWORD': 'Re-taper le nouveau mot de passe',
};
