Map<String, String> german = {
  'WELCOME_BACK': 'Willkommen zurück',
  'HOME': 'Heim',
  'HISTORY': 'Geschichte',
  'PROFILE': 'Profil',
  'COMPLETE_DELIVERY': 'Komplette Lieferung',
  'RETURN_DELIVERY': 'Rücklieferung',
  'ACTIVE_ORDERS': 'Aktive Bestellungen',
  'SEE_DETAILS': 'Siehe Einzelheiten',
  'GET_DIRECTION': 'Richtung erhalten',
  'ORDER_ID': 'Auftragsnummer : ',
  'SEE_ORDER_DETAILS': 'Siehe Bestelldetails',
  'CONFIRM_DELIVERY': 'Lieferung bestätigen',
  'CUSTOMER': 'Kundin',
  'ORDER_DETAILS': 'Bestelldetails',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Ihre voraussichtliche Lieferzeit',
  'PAYMENT_INFO': 'Zahlungsinformationen',
  'METHOD': 'Methode : ',
  'STATUS': 'Status : ',
  'ORDER_SUMMERY': 'Bestellübersicht',
  'SIZE': 'Größe: ',
  'EXTRAS': 'Extras',
  'ADDON': 'Erweiterung: ',
  'INSTRUCTIONS': 'Anweisungen: ',
  'SUBTOTAL': 'Zwischensumme',
  'DISCOUNT': 'Rabatt',
  'DELIVERY_CHARGE': 'Zustellgebühr',
  'TOTAL': 'Gesamt',
  'CONFIRM_DELIVERY_ALERT':
      'Sind Sie sicher, dass Sie die Lieferung bestätigen?',
  'NO_CANCEL': 'Nein, Absagen',
  'YES_CONFIRM': 'Ja, Bestätigen',
  'YES_COLLECT': 'Ja, Collect',
  'CASH_ON_DELIVERY': 'Barzahlung bei Lieferung',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Bestellung erfolgreich geliefert',
  'BACK_TO_HOME': 'Zurück nach Hause',
  'OPEN': 'Offen',
  'MY_PROFILE': 'Mein Profil',
  'BRANCH': 'Zweig',
  'LOG_OUT': 'Ausloggen',
  'ERROR': 'Fehler',
  'SUCCESS': 'Erfolg',
  'CHANGE_PASSWORD': 'Passwort ändern',
  'CHANGE_LANGUAGE': 'Sprache ändern',
  'TERMS_CONDITION': 'Allgemeine Geschäftsbedingungen',
  'PRIVACY_POLICY': 'Datenschutz-Bestimmungen',
  'EDIT_PROFILE': 'Profil bearbeiten',
  'FIRST_NAME': 'Vorname',
  'LAST_NAME': 'Nachname',
  'EMAIL': 'Email',
  'PASSWORD': 'Passwort',
  'MOBILE_NUMBER': 'Handynummer',
  'UPDATE_PROFILE': 'Profil aktualisieren',
  'OLD_PASSWORD': 'Altes Passwort',
  'NEW_PASSWORD': 'Neues Passwort',
  'RETYPE_NEW_PASSWORD': 'Geben Sie das neue Kennwort erneut ein',
  'DELETE_ACCOUNT': 'Löschen Sie Ihr Profil',
  'PROFILE_UPDATE': 'Profil aktualisiert',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Profil erfolgreich aktualisiert',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Passwort erfolgreich aktualisiert',
  'CONFIRM_NEW_PASSWORD': 'Bestätige neues Passwort',
  'PLEASE_ENTER_VALID_INPUT': 'Bitte geben Sie eine gültige Eingabe ein',
  'PRESS_BACK_AGAIN_TO_EXIT':
      'Drücken Sie erneut die Zurück-Taste, um den Vorgang zu beenden.',
  'REMEMBER_ME': 'Mich erinnern',
  'ORDER_HISTORY': 'Bestellverlauf',
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": 'Das Bild sollte weniger als 2 MB groß sein',
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": 'Profilbild erfolgreich gespeichert',
  'SOMETHING_WRONG': 'Stimmt etwas nicht',
  "YOU_HAVE_NO_ORDER_FOR_DELIVERY": "Sie haben keinen Lieferauftrag",
  "WAIT_NOTE":
      "Warten Sie, bis Ihr Filialleiter Ihnen die Bestellung zur Lieferung übermittelt.",
  "YOU_HAVE_NO_ORDER_HISTORY": "Sie haben keine Bestellhistorie",
  "ALL_BRANCH": "Alle Zweigstellen",
  "INSTRUCTION": "Anweisung",
  "DELIVERY_ADDRESS": "Lieferadresse",
  "PAID": "Bezahlt",
  "UNPAID": "Unbezahlt",
  "PICK_PAY": "Pick & Pay",
  "DO_YOU_COLLECT_PAYMENT": "Haben Sie die Zahlung eingezogen?",
  "AMOUNT": "Menge",
  "PLEASE_TYPE_FIRST_NAME": "Bitte geben Sie Ihren Vornamen ein",
  "PLEASE_TYPE_LAST_NAME": "Bitte geben Sie Ihren Nachnamen ein",
  "PLEASE_TYPE_EMAIL": "Bitte geben Sie Ihre E-Mail-Adresse ein",
  "PLEASE_TYPE_OLD_PASSWORD": "Bitte geben Sie das alte Passwort ein",
  "PLEASE_TYPE_NEW_PASSWORD": "Bitte geben Sie Ihr neues Passwort ein",
  "PLEASE_RETYPE_PASSWORD": "Bitte geben Sie das Passwort erneut ein",
  "PASSWORD_MUST_BE_SIX": "Das Passwort muss mindestens 6 Zeichen lang sein",
  "ENTER_VALID_EMAIL": "Geben Sie eine gültige E-Mail-Adresse ein",
  "PLEASE_TYPE_PASSWORD": "Bitte geben Sie das Passwort ein",
  "LOCATION_SERVICE_DENIED": "Der Ortungsdienst wird verweigert!",
  "LOCATION_PERMISSION_NOT_ENABLED":
      "Die Standortberechtigung ist nicht aktiviert!",
};
